# Generated by Django 3.2.5 on 2021-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Img',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
